[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
program = "F8PqxjxJbW3bMSkZ5fWLcvL3dZ6N34rrmNGqC33xt4Qw"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
